### ISSUE TITLE
Django Form example issue

### ISSUE THREAD

**Issue by ephess** [jorgebastida/dajaxproject.com#3]
Hi There,

Just been working through the django form example in my site and was having issues passing the serialized form into a django form object.. figured I needed to deserialize it somehow but couldn't find a way to do it in any documentation anywhere.

Finally found it looking through the source for the site:

https://github.com/jorgebastida/dajaxproject.com/blob/master/examples/ajax.py#L57

Would be good if this were updated on the main site:

http://www.dajaxproject.com/fullform/

Thanks for making such a great tool :)

**Comment by jorgebastida** [comment]
Hello @ephess 

I've update dajaxproject.com: https://github.com/jorgebastida/dajaxproject.com/commit/2e0259ca82920371fe01d39a4e35f6fb0e457a9c and also add this function to the documentation https://github.com/jorgebastida/django-dajaxice/commit/238397b7d1f1e4770de2e8b9d684d1e187c5dd83

Thank you very much!

**Comment by ephess** [comment]
Thank you!! :)
